# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://subwave07.github.io/easycloud/
title: EasyCloud
email: your-email@domain.com
author: subwave07
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2019 <a href="https://www.uniupo.it">University of the Eastern Piedmont</a>. All Rights Reserved.<br/>All other marks may be trademarks or registered trademarks of their respective owners.'
credits: Landing Page Theme by <a href="https://startbootstrap.com">Start Bootstrap</a><br/>Cloud photo by <a href="https://unsplash.com/@alexmachado">Alex Machado</a> at <a href="https://unsplash.com">Unsplash.com</a><br/>Presentation images by <a href="https://magicmockups.com">Magicmockups.com</a>
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
